apiVersion: v1
kind: Namespace
metadata:
  name: marine-farming-stable

---

apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: marine-farming-stable
data:
  .dockerconfigjson: {{dockerconfigjson}}
type: kubernetes.io/dockerconfigjson

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: laravel-pv-claim-dev
  namespace: marine-farming-stable
  labels:
    app.kubernetes.io/name: laravel-stable
    app.kubernetes.io/instance: marine-farming-api-stable
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: laravel
    app.kubernetes.io/part-of: marine-farming
    app.kubernetes.io/managed-by: docker
    environment: staging
    tier: pvc
    partition: marine-farming
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: laravel-stable
    app.kubernetes.io/instance: marine-farming-api-stable
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: laravel
    app.kubernetes.io/part-of: marine-farming
    app.kubernetes.io/managed-by: docker
    environment: staging
    tier: backend
    partition: marine-farming
  name: laravel-stable
  namespace: marine-farming-stable
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: laravel-stable
  template:
    metadata:
      labels:
        app.kubernetes.io/name: laravel-stable
    spec:
      containers:
        - name: laravel
          image: {{image}}
          imagePullPolicy: "Always"
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /var/www/html
              name: laravel-stable-persistent-storage
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r /var/www/marine-farming-api/. /var/www/html && chown -R www-data:www-data /var/www/html && chmod -R 775 /var/www/html/storage /var/www/html/bootstrap && php artisan migrate:fresh --seed --no-interaction && php artisan passport:install --force && php artisan passport:keys --force && php artisan passport:client --password --no-interaction && php artisan cache:clear && php artisan config:clear && php artisan route:clear && php artisan storage:link && php artisan config:cache && php artisan route:cache"]
        - name: nginx
          image: {{nginx_image}}
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: laravel-stable-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: laravel-stable-persistent-storage
          emptyDir: {}
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: laravel-stable
    app.kubernetes.io/instance: marine-farming-api-stable
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: laravel
    app.kubernetes.io/part-of: marine-farming
    app.kubernetes.io/managed-by: docker
    environment: staging
    tier: frontend
    partition: marine-farming
  name: laravel-stable
  namespace: marine-farming-stable
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: laravel-stable

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: marine-farming-api-stable-ingress
  namespace: marine-farming-stable
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
    cert-manager.io/cluster-issuer: letsencrypt-production
#    nginx.ingress.kubernetes.io/enable-cors: "true"
  labels:
    environment: staging
    tier: ingress
    partition: marine-farming
spec:
  tls:
    - hosts:
        - {{host}}
      secretName: marine-farming-api-stable-tls
  rules:
    - host: {{host}}
      http:
        paths:
          - backend:
              serviceName: laravel-stable
              servicePort: 80
