apiVersion: v1
kind: Namespace
metadata:
  name: marine-farming

---

apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: marine-farming
data:
  .dockerconfigjson: {{dockerconfigjson}}
type: kubernetes.io/dockerconfigjson

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: phppgadmin
    app.kubernetes.io/instance: marine-farming-api
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: phppgadmin
    app.kubernetes.io/part-of: marine-farming
    app.kubernetes.io/managed-by: docker
    environment: staging
    tier: backend
    partition: marine-farming
  name: phppgadmin
  namespace: marine-farming
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: phppgadmin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: phppgadmin
    spec:
      containers:
        - name: phppgadmin
          image: {{phppgadmin_image}}
          imagePullPolicy: "Always"
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: laravel-persistent-storage
              mountPath: /var/www/html
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r /var/www/phppgadmin/. /var/www/html && chown -R www-data:www-data /var/www/html"]
        - name: nginx
          image: {{phppgadmin_nginx_image}}
          imagePullPolicy: "Always"
          volumeMounts:
            - name: laravel-persistent-storage
              mountPath: /var/www/html
          ports:
            - containerPort: 80
      volumes:
        - name: laravel-persistent-storage
          emptyDir: {}
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: phppgadmin
    app.kubernetes.io/instance: marine-farming-api
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: phppgadmin
    app.kubernetes.io/part-of: marine-farming
    app.kubernetes.io/managed-by: docker
    environment: staging
    tier: frontend
    partition: marine-farming
  name: phppgadmin
  namespace: marine-farming
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: phppgadmin

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: marine-farming-database-ingress
  namespace: marine-farming
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
  labels:
    environment: staging
    tier: ingress
    partition: marine-farming
spec:
  tls:
    - hosts:
        - db.{{host}}
      secretName: marine-farming-database-tls
  rules:
    - host: db.{{host}}
      http:
        paths:
          - backend:
              serviceName: phppgadmin
              servicePort: 80
